require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require "json"
app_config = JSON.parse(File.read(File.join(__dir__, '..', 'src', 'config', "AppConfig.json")))

platform :ios, '14.0'

target 'TravelApp' do
#  pod 'onnxruntime-mobile-objc'
  config = use_native_modules!
reactNativePath = config["reactNativePath"] ||= "../node_modules/react-native"
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
 
 

  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'
  pod 'react-native-image-editor', :path => '../node_modules/@react-native-community/image-editor'
  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'ReactCommon/turbomodule/core', :path => "#{reactNativePath}/ReactCommon", :modular_headers => true



  target 'TravelAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()
  
    post_install do |installer|
      react_native_post_install(installer)
          installer.pods_project.build_configurations.each do |config| config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] =  "arm64"
          end
    end
end
